#ifndef __DICTIONARY_DB_CODES_H__
#define __DICTIONARY_DB_CODES_H__

#define KEY_ARROW_UP 72
#define KEY_ARROW_LEFT 75
#define KEY_ARROW_RIGHT 77
#define KEY_ARROW_DOWN 80

#define KEY_TAB 9
#define KEY_ENTER 13
#define KEY_ESC 27
#define KEY_BACKSPACE 8
#define KEY_SPACE 32
#define KEY_DEL 83

#define KEY_F1  59
#define KEY_F2  60
#define KEY_F3  61
#define KEY_F4  62
#define KEY_F5  63
#define KEY_F6  64
#define KEY_F7  65
#define KEY_F8  66
#define KEY_F9  67
#define KEY_F10 68
#define KEY_F11 133
#define KEY_F12 134

#define CHAR_BORDER_HORZ 205
#define CHAR_BORDER_VERT 186
#define CHAR_BORDER_LEFT_TOP 201
#define CHAR_BORDER_LEFT_BOTTOM 200
#define CHAR_BORDER_RIGHT_TOP 187
#define CHAR_BORDER_RIGHT_BOTTOM 188
#define CHAR_BORDER_LEFT_JOINT 204
#define CHAR_BORDER_RIGHT_JOINT 185
#define CHAR_BORDER_TOP_JOINT 203
#define CHAR_BORDER_BOTTOM_JOINT 202
#define CHAR_BORDER_CROSS_JOINT 206

#endif // __DICTIONARY_DB_KEY_CODES_H__

